name: Health check

on:
  schedule:
    - cron: '0 11 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-open-pokedex-web-service.onrender.com/health
          max-attempts: 2
