name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npx playwright test
      - name: Deploy
        if: github.ref == 'refs/heads/main' && contains(join(github.event.commits.*.message), '#skip') == false
        run: curl "$deploy_url"
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      - name: Notify Discord on success
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          username: GitHub Actions
          title: 'Deploy succeeded 😎'
          description: 'A new version of Pokedex is live!'
          color: 0x00ff00
      - name: Notify Discord on failure
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          username: GitHub Actions
          title: 'Deploy failed 👺'
          description: 'Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})'
          url: 'https://github.com/jv-soares/full-stack-open-pokedex'
          color: 0xff0000

  tag_release:
    if: github.ref == 'refs/heads/main' && contains(join(github.event.commits.*.message), '#skip') == false
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
